version: '3.7'

services:
  dating_db:
    image: postgres:latest
    container_name: dating_db
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - dating_db_data:/var/lib/postgresql/data/
volumes:
  dating_db_data: